### ISSUE TITLE
Parameter not valid exception

### ISSUE THREAD

**Issue by cliftonm** [cliftonm/FlowSharp#44]
![fsbug](https://cloud.githubusercontent.com/assets/3474356/20038721/8403838a-a406-11e6-9810-b619875e455a.png)

This exception occurred while fussing with the vertical line shape.  I haven't figured out how to reproduce it.

**Comment by qwertie** [comment]
Interestingly, I most often got the "Parameter is not valid" crash when deleting shapes. I assume it was triggered by something that was done earlier that presumably corrupted something.
