### ISSUE TITLE
Snap behavior

### ISSUE THREAD

**Issue by cliftonm** [cliftonm/FlowSharp#6]
If connection points of the group box and the inner children are too close together, a connector
snaps to the wrong connection point.  Need to snap to the nearest connection, not just the first near connection.

**Comment by qwertie** [comment]
Yup, this was bothering as I drew my first diagram today, especially since the snapping radius is large-ish.

**Comment by cliftonm** [comment]
See also Issue #32.

**Comment by cliftonm** [comment]
One comment about this - snapping now happens to the nearest connection point on the shape, so depending on which direction you approach two very close connection points, the connector snaps to the nearest one now.
