### ISSUE TITLE
MIT or BSD or Apache2 license request

### ISSUE THREAD

**Issue by prepare** [cliftonm/FlowSharp#71]
This project uses The Code Project Open License (CPOL) 1.02. (http://htmlpreview.github.io/?http://www.codeproject.com/info/cpol10.aspx)
I think the license is a mild copyleft license, similar to Mozilla license.

Would you mind if I ask you to change the license to other non-copyleft one?
eg. MIT, BSD, Apache2 etc.

:)

**Comment by cliftonm** [comment]
What are the cons of using CPOL and the pros of using MIT/BSD/etc.?

**Comment by prepare** [comment]
I think CPOL is a 'mild' copyleft license, similar to Mozilla license.

cons: 
since its copyleft, even mild, some new derivative works/ modification
must have the same license,

>  License Grant. ...
   c) You may otherwise modify Your copy of this Work (excluding the Articles) in any way to create a Derivative Work, provided that You insert a prominent notice in each changed file stating how, when and where You changed that file.

and its derivative must be open source too.

> d) You may distribute the standard version of the Executable Files and Source Code or Derivative Work in aggregate with other (possibly commercial) programs as part of a larger (possibly commercial) software distribution. 
  
sometime this license type is not attractive to the developers who develops both
open source version and proprietary version.

---
pros of MIT/BSD/Apache2 etc..

they have more freedom of choices to integrate the code.
(They don't force the devs to give back the code all times)
It is attractive to both open source project and proprietary project.
 

I think many new projects these days go this way.
(eg Microsoft .NET framework : MIT,  
      Microsoft Roslyn : Apache2)

and I also have many projects with these kind of licenses too.
(eg. https://github.com/LayoutFarm/HtmlRenderer , https://github.com/LayoutFarm/Typography)
 
---

WinterDev
:)

**Comment by cliftonm** [comment]
Well, that makes sense, but reading https://en.wikipedia.org/wiki/Code_Project_Open_License the only major restriction that I see is that you can't simply take the code as is and sell it, which works well for me in this case, particularly since FlowSharp is an application, not just a code library or code fragment.

That said, if there is a need for a difference license, I'm open to providing an exemption or alternative license terms on an as-needed basis.

(BTW, I took a quick look at your projects, very impressive!)

**Comment by prepare** [comment]
> That said, if there is a need for a difference license, I'm open to providing an exemption or alternative license terms on an as-needed basis.

👍
